# Generated by Django 5.0.4 on 2024-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='authentication.myuser'),
        ),
    ]
